version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: scrypt
    versions:
    - 0.6.0
    - 0.6.1
    - 0.6.4
  - dependency-name: sha-1
    versions:
    - 0.9.3
