[package]
name = "f2"
version = "2.4.1"
authors = ["Naitik Shah <n@daaku.org>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1.0"
base32 = "0.4"
base64 = "0.13"
chacha20poly1305 = "0.7"
crypto-mac = "0.10"
csv = "1.1"
dirs-next = "2.0"
hmac = "0.10"
lazy_static = "1.4"
prettytable-rs = "0.8"
rand = "0.7"
rpassword = "5.0"
rprompt = "1.0"
scrypt = "0.5"
self_update = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
sha-1 = "0.9"
structopt = "0.3"
structopt-derive = "0.4"

[profile.release]
lto = true
