[package]
name = "f2"
version = "1.0.8"
authors = ["Naitik Shah <n@daaku.org>"]
edition = "2018"
license = "MIT"

[dependencies]
base32 = "0.4"
base64 = "0.10"
hmac = "0.7"
lazy_static = "1.4"
prettytable-rs = "0.8"
rand = "0.7"
rpassword = "4.0"
rprompt = "1.0"
scrypt = "0.2"
secretbox = { git = "https://gitlab.com/daaku/secretbox", rev = "ea76e572" }
self_update = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha-1 = "0.8"
string-error = "0.1"
structopt = "0.3"
structopt-derive = "0.3"

[profile.release]
lto = true
