[package]
name = "f2"
version = "1.0.16"
authors = ["Naitik Shah <n@daaku.org>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1.0"
base32 = "0.4"
base64 = "0.12"
dirs-next = "1.0"
hmac = "0.7"
lazy_static = "1.4"
prettytable-rs = "0.8"
rand = "0.7"
rpassword = "4.0"
rprompt = "1.0"
scrypt = "0.2"
secretbox = "0.1"
self_update = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
sha-1 = "0.8"
structopt = "0.3"
structopt-derive = "0.4"

[profile.release]
lto = true
