name: Build
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          components: clippy
      - name: Build
        run: cargo build
      - name: Clippy
        run: cargo clippy
      - name: Test
        run: cargo test
