name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: f2
            asset_name: f2-x86_64-unknown-linux-gnu
          - os: macos-latest
            artifact_name: f2
            asset_name: f2-x86_64-apple-darwin
          - os: windows-latest
            artifact_name: f2.exe
            asset_name: f2-x86_64-pc-windows-msvc.exe

    steps:
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          components: clippy
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Strip
        if: (contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu'))
        run: strip target/release/${{ matrix.artifact_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.6.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.event.ref }}
