name: Release
on:
  create:
    tags:
jobs:
  build:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: f2
            asset_name: f2-x86_64-unknown-linux-gnu
          - os: macos-latest
            artifact_name: f2
            asset_name: f2-x86_64-apple-darwin
          - os: windows-latest
            artifact_name: f2.exe
            asset_name: f2-windows-amd64.exe

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.event.ref }}
